### ISSUE TITLE
SF-RCV

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#16]
**What is the feature or problem to solve?**
RCV contests will be present on the November ballot for San Francisco. We need to support marking on VxMark and scanning tabulation on VxCentralScan/VxAdmin. 

**Why is it important?**
We cannot support with the San Francisco pilot without this feature.

### Related VVSG Requirements
* 1.1.4-M: For a ranked choice voting (RCV) contest, the voting system must be capable of gathering and recording votes in a contest where the voter must be able to rank contest selections in order of preference, as first choice, second choice, etc.
* 1.1.8-J: For ranked choice voting (RCV), the voting system must: 1/ capture the voter’s ranking of each contest selection and store it in the CVR associated with the ballot style 2/ aggregate 1st choice totals of each contest selection 3/ process the collection of CVRs round-by-round according to the method specified in the implementation statement. Ranked choice voting (RCV) tabulation methods are different for single seat and multi-seat contests.  Jurisdictional rules vary even when using the same basic method. A voting unit or precinct tabulating unit cannot perform RCV tabulation.  RCV tabulation requires the concurrent availability of all CVRs associated with an RCV contest and is a post-voting accumulation/aggregation process.  Some jurisdictional rules may only require use of the RCV tabulation process if aggregated first choice selections do not produce the total needed to exceed the threshold of votes required to win. Other jurisdictional rules do not use tabulated and aggregated 1st choice selections and require the RCV tabulation process to be used for all winners.  Single winner RCV is also known as IRV (Instant Runoff Voting).  STV (Single Transferable Vote) is a method used for multi-winner RCV.  Another multi-winner process (Sequential At-Large IRV) uses successive IRV passes, one pass to determine each winner.

**Comment by cjerdonek** [comment]
Was this supposed to be added to the SF Pilot milestone?
