### ISSUE TITLE
New Hampshire Ballot Scanning Prototype

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#6]
**What is the feature or problem to solve?**
Ballot scanning of New Hampshire SOS produced Accuvote style ballots.

Demo plan defined here: https://docs.google.com/document/d/1_mFGPv2W1epCWCAjQhaXvjj16Or3NUO0dBI0BN3vA2Y/edit

**Why is it important?**
Scanning ballots in this format is required for New Hampshire certification and we are scheduling an initial certification hearing in April. This supports our company goal of getting certified in one state this year.

**Comment by eventualbuddha** [comment]
I'm declaring this "done". Any additional work to be done on it can be handled separately.
