### ISSUE TITLE
RLAbility

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#64]
- [x] https://github.com/votingworks/vxsuite/issues/1520

### VVSG Requirements
- TA94A-1: IF a voting system uses a paper-based architecture, THEN the system MUST support an evidence-based election, which allows election officials to conduct a risk-limiting audit.
- TA94A-1-1: A voting system MAY be considered “efficient” IF it meets requirements 4.1- C - Exchange of cast vote records (CVRs), 9.4-C - Unique ballot identifiers, and 9.4-D -Multipage ballots.
- TA94C-1: The voting system MUST EITHER have the capability of preserving the ballot scanning order or MUST be capable of affixing a unique ballot identifier such as scanner ID, batch ID, or ballot card number.
- TA94D-1-1: For multipage ballot cards, the voting system MUST affix/apply EITHER page numbers or other form of ballot card identifier to keep multipage ballot cards together.
- TA94D-1-2: The voting system MUST EITHER preserve the order of ballots scanned or MUST be capable of affixing a unique ballot identifier to each page of a multipage ballot as per 9.4-C - Unique ballot identifiers.
- TA94D-1-3: The voting system MUST specify the affixed page number or unique ballot card identifier for each record in the CVR report.

**Comment by mattroe** [comment]
https://github.com/votingworks/vxsuite/issues/1520

**Comment by adghayes** [comment]
@mattroe @carolinemodic , https://github.com/votingworks/vxsuite/issues/1520 is closed. Not sure if that affects the status of this roadmap item, or if you need to keep it open in relation to the imprinting work.

**Comment by mattroe** [comment]
Will close - the imprinting unique identifier stuff is tracked in https://github.com/votingworks/vxsuite-roadmap/issues/31
